name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ianwalter/puppeteer@v2.0.0
        with:
          entrypoint: /bin/make
          args: ci
