name: build

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: tacoss/nodejs@master
        env:
          BROWSER: chromium:headless
          NODE_ENV: development
        with:
          args: ci
